---
# tasks file for ansible-role-sensu-client

- include_vars: "{{ ansible_os_family }}.yml"

- include: "install-{{ ansible_os_family }}.yml"

- name: Create sensu_client_conf_d_dir
  file:
    path: "{{ sensu_client_conf_d_dir }}"
    owner: "{{ sensu_client_user }}"
    group: "{{ sensu_client_group }}"
    state: directory

- name: Create sensu_client_extensions_dir
  file:
    path: "{{ sensu_client_extensions_dir }}"
    owner: "{{ sensu_client_user }}"
    group: "{{ sensu_client_group }}"
    state: directory

- name: Create sensu_client_plugins_dir
  file:
    path: "{{ sensu_client_plugins_dir }}"
    owner: "{{ sensu_client_user }}"
    group: "{{ sensu_client_group }}"
    state: directory

- name: Create sensu_client_config_file
  template:
    src: config.json.j2
    dest: "{{ sensu_client_config_file }}"
    validate: "python -c 'import sys; import json; json.loads(open(sys.argv[1]).read())' %s"
  notify: Restart sensu services


- name: Create sensu_client_log_dir
  file:
    path: "{{ sensu_client_log_dir }}"
    state: directory
    owner: "{{ sensu_client_user }}"
    group: "{{ sensu_client_group }}"

- name: Create json files
  template:
    src: json.j2
    dest: "{{ sensu_client_conf_d_dir }}/{{ item }}.json"
    validate: "python -c 'import sys; import json; json.loads(open(sys.argv[1]).read())' %s"
  with_items: "{{ sensu_client_config_fragments.keys() }}"
  notify: Restart sensu services

- include: "plugins.yml"

- name: Start sensu-client
  service:
    name: "{{ sensu_client_service }}"
    enabled: true
    state: started
