---
# tasks file for ansible-role-sensu-client

- include_vars: "{{ ansible_os_family }}.yml"

- include: "install-{{ ansible_os_family }}.yml"

- name: Create log directory
  file:
    path: "{{ sensu-client_log_dir }}"
    mode: 0755
    owner: "{{ sensu-client_user }}"
    group: "{{ sensu-client_group }}"
    state: directory
  notify: Restart sensu-client

- name: Create db directory
  file:
    path: "{{ sensu-client_db_dir }}"
    mode: 0755
    owner: "{{ sensu-client_user }}"
    group: "{{ sensu-client_group }}"
    state: directory
  notify: Restart sensu-client

- name: Create sensu-client.conf
  template:
    src: sensu-client.conf.j2
    dest: "{{ sensu-client_conf_file }}"
    validate: echo %s
  notify: Restart sensu-client

- name: Start sensu-client
  service:
    name: "{{ sensu-client_service }}"
    enabled: true
    state: started
